version: "3"

services:
  mariadb:
    image: mariadb
    container_name: db_cont
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception-network
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wp_cont
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_files:/www/wordpress
    networks:
      - inception-network
    ports:
      - "9000"
    restart: on-failure

  nginx:
    image: nginx
    container_name: ng_cont
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - wordpress_files:/www
    networks:
      - inception-network
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gusta/data/DB/
#      device: /home/gusousa/data/DB/

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gusta/data/wordpress_files/
      #device: /home/gusousa/data/wordpress_files/


networks:
  inception-network:
    name: inception-network
